CREATE OR REPLACE PROCEDURE EXTRACT_DATA(TABLE_NAME STRING,FILE_NAME STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
LOADING_STMT STRING;
COUNT_ROWS INT;
TASK_INITIATED DATETIME;
TASK_FINISHED DATETIME;
TO_GET_USER STRING;
BEGIN
        TASK_INITIATED := CURRENT_TIMESTAMP();

        TO_GET_USER := CURRENT_USER();


        LOADING_STMT := 'COPY INTO ' || TABLE_NAME || 
                        ' FROM @my_s3_stage' ||
                        ' FILES = (''' || FILE_NAME || ''')';

        EXECUTE IMMEDIATE LOADING_STMT;


        COUNT_ROWS := sqlrowcount;

        
        TASK_FINISHED := CURRENT_TIMESTAMP();

        INSERT INTO AUDIT_TABLE (TABLEE_NAME,FILEE_NAME,ACTION_TYPE,SOURCE_COUNT,STATUS,START_TIME,END_TIME,ERROR_MESSAGE)
        VALUES (:TABLE_NAME,:FILE_NAME,'Data_Loading',:COUNT_ROWS,'Sucess',:TASK_INITIATED,:TASK_FINISHED,NULL);

        CALL SYSTEM$SEND_EMAIL('ALERT_USER','subhashv9966@gmail.com','REGARDING_LOADING_DATA',
        'FROM_USER : ' || :TO_GET_USER || CHAR(10) ||
        'TABLE_NAME : ' || :TABLE_NAME || char(10) ||
        'FILE_NAME : ' || :FILE_NAME || char(10) ||
        'NO_OF_ROWS_LOADED : ' || :COUNT_ROWS || char(10) ||
        'STATUS : SUCESS');

        RETURN FILE_NAME || 'LOADED SUCESSFULLY';
EXCEPTION
WHEN OTHER THEN 
TASK_FINISHED := CURRENT_TIMESTAMP();
INSERT INTO AUDIT_TABLE (TABLEE_NAME,FILEE_NAME,ACTION_TYPE,SOURCE_COUNT,STATUS,START_TIME,END_TIME,ERROR_MESSAGE)
        VALUES (:TABLE_NAME,:FILE_NAME,'Data_Loading',NULL,'Failed',:TASK_INITIATED,:TASK_FINISHED,:SQLERRM);

CALL SYSTEM$SEND_EMAIL('ALERT_USER','subhashv9966@gmail.com','REGARDING_LOADING_DATA',
        'FROM_USER : ' || :TO_GET_USER || CHAR(10) ||
        'TABLE_NAME : ' || :TABLE_NAME || char(10) ||
        ' FILE_NAME : ' || :FILE_NAME || char(10) ||
        ' STATUS : FAILED' || char(10) ||
        ' ERROR MESSAGE' || :SQLERRM);


        RETURN SQLERRM;
END;
$$;

CALL EXTRACT_DATA('sales_data','retail_sales_dataset.csv');


SELECT * FROM SALES_DATA;


SELECT * FROM AUDIT_TABLE;



